# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-19 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0001_initial'),
        ('cleaners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='towns',
            field=models.ManyToManyField(related_name='towns', to='towns.Town'),
        ),
    ]
